# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1020, 680)
        MainWindow.setMinimumSize(QtCore.QSize(1020, 680))
        MainWindow.setStyleSheet("QScrollBar:horizontal{\n"
"    height:8px;\n"
"    background:rgba(0,0,0,0%);\n"
"border-radius:4px;\n"
"\n"
"}\n"
"QScrollBar::handle:horizontal{\n"
"    background:rgba(255,255,255,50%);\n"
"border-radius:4px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover{\n"
"    background:rgba(255,255,255,100%);\n"
"    min-width:0;\n"
"}\n"
"QScrollBar::add-line:horizontal{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::sub-line:horizontal{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::add-line:horizontal:hover{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::add-page:horizontal,QScrollBar::sub-page:horizontal\n"
"{\n"
"    background:rgba(0,0,0,10%);\n"
"    border-radius:4px;\n"
"}\n"
"\n"
"QScrollBar:vertical{\n"
"    width:8px;\n"
"    background:rgba(0,0,0,0%);\n"
"\n"
"}\n"
"QScrollBar::handle:vertical{\n"
"    width:0px;\n"
"    background:rgba(255,255,255,50%);\n"
"    border-radius:4px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{\n"
"    width:0px;\n"
"    background:rgba(255,255,255,100%);\n"
"    border-radius:4px;\n"
"    min-width:20;\n"
"}\n"
"QScrollBar::add-line:vertical{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::sub-line:vertical{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::add-line:vertical:hover{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::sub-line:vertical:hover{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::add-page:vertical,QScrollBar::sub-page:vertical\n"
"{\n"
"    background:rgba(0,0,0,10%);\n"
"    border-radius:4px;\n"
"}\n"
"\n"
" \n"
" \n"
"QSlider::add-page:horizontal {\n"
"    background-color: qlineargradient(spread: pad, x1: 0, y1: 1, x2: 1, y2: 1,\n"
"                                      stop: 0 rgb(100, 100, 100),\n"
"                                      stop: 1 rgb(255, 78, 0,));\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background-color: qlineargradient(spread: pad, x1: 0, y1: 1, x2: 1, y2: 1,\n"
"                                      stop: 0 rgb(51, 151, 255),\n"
"                                      stop: 1 rgb(100, 100, 100));\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    background: transparent;\n"
"    height: 8px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    width: 16px;\n"
"    height: 18px;\n"
"    margin: -4px 0px -4px 0px;\n"
"    border-radius: 8px;\n"
"    background: white;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMouseTracking(True)
        self.centralwidget.setAcceptDrops(True)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: rgba(112, 112, 112, 255);\n"
"    border:none;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_menu = QtWidgets.QFrame(self.frame)
        self.frame_menu.setStyleSheet(".QFrame#frame_menu{\n"
"    background-color:rgb(32, 32, 32);\n"
"}")
        self.frame_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu.setObjectName("frame_menu")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_menu)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.frame_menu)
        self.widget.setMinimumSize(QtCore.QSize(40, 0))
        self.widget.setStyleSheet("image:url(:/images/icon/image_photo_picture_gallery_icon.png)")
        self.widget.setObjectName("widget")
        self.horizontalLayout.addWidget(self.widget)
        self.label_logo = QtWidgets.QLabel(self.frame_menu)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_logo.setFont(font)
        self.label_logo.setStyleSheet("QLabel{\n"
"    background-color:transparent;\n"
"    color:rgb(255, 255, 255);\n"
"}")
        self.label_logo.setWordWrap(False)
        self.label_logo.setObjectName("label_logo")
        self.horizontalLayout.addWidget(self.label_logo)
        self.horizontalLayout_10.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_min_2 = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_min_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_min_2.setToolTipDuration(3000)
        self.pushButton_min_2.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_min_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icon/zoom_in_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_min_2.setIcon(icon)
        self.pushButton_min_2.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_min_2.setFlat(True)
        self.pushButton_min_2.setObjectName("pushButton_min_2")
        self.horizontalLayout_3.addWidget(self.pushButton_min_2)
        self.pushButton_min_3 = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_min_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_min_3.setToolTipDuration(3000)
        self.pushButton_min_3.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_min_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/icon/zoom_out_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_min_3.setIcon(icon1)
        self.pushButton_min_3.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_min_3.setFlat(True)
        self.pushButton_min_3.setObjectName("pushButton_min_3")
        self.horizontalLayout_3.addWidget(self.pushButton_min_3)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_min = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_min.setToolTipDuration(3000)
        self.pushButton_min.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}\n"
".QPushButton:pressed{\n"
"    background-color:rgb(90, 90, 90);\n"
"    border-radius:10px;\n"
"}\n"
".QPushButton:normal{\n"
"    background-color:transparent;\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_min.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/icon/minus_delete_remove_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_min.setIcon(icon2)
        self.pushButton_min.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_min.setDefault(False)
        self.pushButton_min.setFlat(True)
        self.pushButton_min.setObjectName("pushButton_min")
        self.horizontalLayout_2.addWidget(self.pushButton_min)
        self.pushButton_max = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_max.setToolTipDuration(3000)
        self.pushButton_max.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}\n"
".QPushButton:pressed{\n"
"    background-color:rgb(90, 90, 90);\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_max.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/icon/maximize_expand_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/images/icon/minimize_2_reduce_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_max.setIcon(icon3)
        self.pushButton_max.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_max.setFlat(True)
        self.pushButton_max.setObjectName("pushButton_max")
        self.horizontalLayout_2.addWidget(self.pushButton_max)
        self.pushButton_close = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_close.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_close.setToolTipDuration(3000)
        self.pushButton_close.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(255, 0, 0);\n"
"    border-radius:10px;\n"
"}\n"
".QPushButton:pressed{\n"
"    background-color:rgba(255, 0, 0, 190);\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_close.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/icon/close_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_close.setIcon(icon4)
        self.pushButton_close.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_close.setFlat(True)
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout_2.addWidget(self.pushButton_close)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.frame_menu)
        self.widget_view = QtWidgets.QWidget(self.frame)
        self.widget_view.setObjectName("widget_view")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_view)
        self.horizontalLayout_8.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.main_stacked_widget = QtWidgets.QStackedWidget(self.widget_view)
        self.main_stacked_widget.setStyleSheet("QWidget{\n"
"    background-color: transparent;\n"
"}")
        self.main_stacked_widget.setObjectName("main_stacked_widget")
        self.page_upload = QtWidgets.QWidget()
        self.page_upload.setObjectName("page_upload")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.page_upload)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.main_stacked_widget.addWidget(self.page_upload)
        self.page_image_view = QtWidgets.QWidget()
        self.page_image_view.setObjectName("page_image_view")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.page_image_view)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.graphicsView = QtWidgets.QGraphicsView(self.page_image_view)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout_12.addWidget(self.graphicsView)
        self.main_stacked_widget.addWidget(self.page_image_view)
        self.page_basic_function = QtWidgets.QWidget()
        self.page_basic_function.setObjectName("page_basic_function")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_basic_function)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.page_basic_function)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.verticalLayout_3.addWidget(self.graphicsView_2)
        self.basic_function_stack = QtWidgets.QStackedWidget(self.page_basic_function)
        self.basic_function_stack.setStyleSheet("QStackedWidget{\n"
"    background-color:transparent;\n"
"}")
        self.basic_function_stack.setObjectName("basic_function_stack")
        self.page_crop = QtWidgets.QWidget()
        self.page_crop.setObjectName("page_crop")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.page_crop)
        self.horizontalLayout_13.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem2 = QtWidgets.QSpacerItem(404, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem2)
        self.widget_2 = QtWidgets.QWidget(self.page_crop)
        self.widget_2.setMinimumSize(QtCore.QSize(150, 0))
        self.widget_2.setStyleSheet("QWidget{\n"
"    background-color: rgb(32, 32, 32);\n"
"    border-radius:25px;\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_15.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.pushButton_min_4 = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_min_4.sizePolicy().hasHeightForWidth())
        self.pushButton_min_4.setSizePolicy(sizePolicy)
        self.pushButton_min_4.setMinimumSize(QtCore.QSize(48, 44))
        self.pushButton_min_4.setMaximumSize(QtCore.QSize(48, 44))
        self.pushButton_min_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_min_4.setToolTipDuration(3000)
        self.pushButton_min_4.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_min_4.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/icon/apply_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_min_4.setIcon(icon5)
        self.pushButton_min_4.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_min_4.setFlat(True)
        self.pushButton_min_4.setObjectName("pushButton_min_4")
        self.horizontalLayout_15.addWidget(self.pushButton_min_4)
        self.pushButton_min_5 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_min_5.setMinimumSize(QtCore.QSize(48, 44))
        self.pushButton_min_5.setMaximumSize(QtCore.QSize(48, 44))
        self.pushButton_min_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_min_5.setToolTipDuration(3000)
        self.pushButton_min_5.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_min_5.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/icon/cancel_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_min_5.setIcon(icon6)
        self.pushButton_min_5.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_min_5.setFlat(True)
        self.pushButton_min_5.setObjectName("pushButton_min_5")
        self.horizontalLayout_15.addWidget(self.pushButton_min_5)
        self.horizontalLayout_13.addWidget(self.widget_2)
        spacerItem3 = QtWidgets.QSpacerItem(404, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem3)
        self.horizontalLayout_13.setStretch(0, 1)
        self.horizontalLayout_13.setStretch(2, 1)
        self.basic_function_stack.addWidget(self.page_crop)
        self.page_rotate = QtWidgets.QWidget()
        self.page_rotate.setObjectName("page_rotate")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.page_rotate)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem4)
        self.widget_4 = QtWidgets.QWidget(self.page_rotate)
        self.widget_4.setMinimumSize(QtCore.QSize(150, 0))
        self.widget_4.setStyleSheet("QWidget{\n"
"    background-color: rgb(32, 32, 32);\n"
"    border-radius:25px;\n"
"}")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_14.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.pushButton_left_90 = QtWidgets.QPushButton(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_left_90.sizePolicy().hasHeightForWidth())
        self.pushButton_left_90.setSizePolicy(sizePolicy)
        self.pushButton_left_90.setMinimumSize(QtCore.QSize(48, 44))
        self.pushButton_left_90.setMaximumSize(QtCore.QSize(48, 44))
        self.pushButton_left_90.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_left_90.setToolTipDuration(3000)
        self.pushButton_left_90.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_left_90.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/icon/rotate_counterclockwise_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_left_90.setIcon(icon7)
        self.pushButton_left_90.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_left_90.setFlat(True)
        self.pushButton_left_90.setObjectName("pushButton_left_90")
        self.horizontalLayout_14.addWidget(self.pushButton_left_90)
        self.pushButton_right_90 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_right_90.setMinimumSize(QtCore.QSize(48, 44))
        self.pushButton_right_90.setMaximumSize(QtCore.QSize(48, 44))
        self.pushButton_right_90.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_right_90.setToolTipDuration(3000)
        self.pushButton_right_90.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_right_90.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/icon/rotate_clockwise_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_right_90.setIcon(icon8)
        self.pushButton_right_90.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_right_90.setFlat(True)
        self.pushButton_right_90.setObjectName("pushButton_right_90")
        self.horizontalLayout_14.addWidget(self.pushButton_right_90)
        self.pushButton_flip_y = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_flip_y.setMinimumSize(QtCore.QSize(48, 44))
        self.pushButton_flip_y.setMaximumSize(QtCore.QSize(48, 44))
        self.pushButton_flip_y.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_flip_y.setToolTipDuration(3000)
        self.pushButton_flip_y.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_flip_y.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/images/icon/ic-flip-x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_flip_y.setIcon(icon9)
        self.pushButton_flip_y.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_flip_y.setFlat(True)
        self.pushButton_flip_y.setObjectName("pushButton_flip_y")
        self.horizontalLayout_14.addWidget(self.pushButton_flip_y)
        self.pushButton_flip_x = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_flip_x.setMinimumSize(QtCore.QSize(48, 44))
        self.pushButton_flip_x.setMaximumSize(QtCore.QSize(48, 44))
        self.pushButton_flip_x.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_flip_x.setToolTipDuration(3000)
        self.pushButton_flip_x.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_flip_x.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/images/icon/ic-flip-y.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_flip_x.setIcon(icon10)
        self.pushButton_flip_x.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_flip_x.setFlat(True)
        self.pushButton_flip_x.setObjectName("pushButton_flip_x")
        self.horizontalLayout_14.addWidget(self.pushButton_flip_x)
        self.horizontalLayout_16.addWidget(self.widget_4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem5)
        self.basic_function_stack.addWidget(self.page_rotate)
        self.verticalLayout_3.addWidget(self.basic_function_stack)
        self.verticalLayout_3.setStretch(0, 1)
        self.main_stacked_widget.addWidget(self.page_basic_function)
        self.page_adjust_function = QtWidgets.QWidget()
        self.page_adjust_function.setObjectName("page_adjust_function")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.page_adjust_function)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.page_adjust_function)
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.horizontalLayout_17.addWidget(self.graphicsView_3)
        self.widget_adjust = QtWidgets.QWidget(self.page_adjust_function)
        self.widget_adjust.setStyleSheet("QWidget{\n"
"    border-radius:20px;\n"
"    background-color: rgb(32, 32, 32);\n"
"}")
        self.widget_adjust.setObjectName("widget_adjust")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.widget_adjust)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.scrollArea = QtWidgets.QScrollArea(self.widget_adjust)
        self.scrollArea.setStyleSheet("QScrollArea{\n"
"    background-color: transparent;\n"
"}")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 230, 1060))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.widget_5 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_5.setMinimumSize(QtCore.QSize(0, 88))
        self.widget_5.setMaximumSize(QtCore.QSize(16777215, 88))
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_image_light = QtWidgets.QLabel(self.widget_5)
        self.label_image_light.setMinimumSize(QtCore.QSize(30, 30))
        self.label_image_light.setStyleSheet("image:url(:/images/icon/bright_light_control_shine_icon.svg)")
        self.label_image_light.setText("")
        self.label_image_light.setObjectName("label_image_light")
        self.horizontalLayout_19.addWidget(self.label_image_light)
        self.label_text_light = QtWidgets.QLabel(self.widget_5)
        self.label_text_light.setMinimumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_text_light.setFont(font)
        self.label_text_light.setStyleSheet("QLabel{\n"
"    color:rgb(255, 255, 255);\n"
"}")
        self.label_text_light.setObjectName("label_text_light")
        self.horizontalLayout_19.addWidget(self.label_text_light)
        self.label_light_perception = QtWidgets.QLabel(self.widget_5)
        self.label_light_perception.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_light_perception.setFont(font)
        self.label_light_perception.setStyleSheet("QLabel{\n"
"    color:rgb(255, 255, 255);\n"
"}")
        self.label_light_perception.setObjectName("label_light_perception")
        self.horizontalLayout_19.addWidget(self.label_light_perception)
        self.horizontalLayout_19.setStretch(0, 1)
        self.horizontalLayout_19.setStretch(1, 5)
        self.horizontalLayout_19.setStretch(2, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_19)
        self.horizontalSlider_light_perception = QtWidgets.QSlider(self.widget_5)
        self.horizontalSlider_light_perception.setStyleSheet("")
        self.horizontalSlider_light_perception.setMinimum(-100)
        self.horizontalSlider_light_perception.setMaximum(100)
        self.horizontalSlider_light_perception.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_light_perception.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_light_perception.setObjectName("horizontalSlider_light_perception")
        self.verticalLayout_4.addWidget(self.horizontalSlider_light_perception)
        self.verticalLayout_15.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_6.setMinimumSize(QtCore.QSize(0, 88))
        self.widget_6.setMaximumSize(QtCore.QSize(16777215, 88))
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_image_brightness = QtWidgets.QLabel(self.widget_6)
        self.label_image_brightness.setMinimumSize(QtCore.QSize(30, 30))
        self.label_image_brightness.setStyleSheet("image:url(:/images/icon/brightness_light_icon.svg)")
        self.label_image_brightness.setText("")
        self.label_image_brightness.setObjectName("label_image_brightness")
        self.horizontalLayout_20.addWidget(self.label_image_brightness)
        self.label_text_brightness = QtWidgets.QLabel(self.widget_6)
        self.label_text_brightness.setMinimumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_text_brightness.setFont(font)
        self.label_text_brightness.setStyleSheet("QLabel{\n"
"    color:rgb(255, 255, 255);\n"
"}")
        self.label_text_brightness.setObjectName("label_text_brightness")
        self.horizontalLayout_20.addWidget(self.label_text_brightness)
        self.label_brightness = QtWidgets.QLabel(self.widget_6)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_brightness.setFont(font)
        self.label_brightness.setStyleSheet("QLabel{\n"
"    color:rgb(255, 255, 255);\n"
"}")
        self.label_brightness.setObjectName("label_brightness")
        self.horizontalLayout_20.addWidget(self.label_brightness)
        self.horizontalLayout_20.setStretch(0, 1)
        self.horizontalLayout_20.setStretch(1, 5)
        self.horizontalLayout_20.setStretch(2, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_20)
        self.horizontalSlider_brightness = QtWidgets.QSlider(self.widget_6)
        self.horizontalSlider_brightness.setStyleSheet("")
        self.horizontalSlider_brightness.setMinimum(-100)
        self.horizontalSlider_brightness.setMaximum(100)
        self.horizontalSlider_brightness.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_brightness.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_brightness.setObjectName("horizontalSlider_brightness")
        self.verticalLayout_5.addWidget(self.horizontalSlider_brightness)
        self.verticalLayout_15.addWidget(self.widget_6)
        self.widget_15 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_15.setMinimumSize(QtCore.QSize(0, 88))
        self.widget_15.setMaximumSize(QtCore.QSize(16777215, 88))
        self.widget_15.setObjectName("widget_15")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_15)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_image_exposure = QtWidgets.QLabel(self.widget_15)
        self.label_image_exposure.setMinimumSize(QtCore.QSize(30, 30))
        self.label_image_exposure.setStyleSheet("image:url(:/images/icon/exposure_icon.svg)")
        self.label_image_exposure.setText("")
        self.label_image_exposure.setObjectName("label_image_exposure")
        self.horizontalLayout_29.addWidget(self.label_image_exposure)
        self.label_text_exposure = QtWidgets.QLabel(self.widget_15)
        self.label_text_exposure.setMinimumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_text_exposure.setFont(font)
        self.label_text_exposure.setStyleSheet("QLabel{\n"
"    color:rgb(255, 255, 255);\n"
"}")
        self.label_text_exposure.setObjectName("label_text_exposure")
        self.horizontalLayout_29.addWidget(self.label_text_exposure)
        self.label_exposure = QtWidgets.QLabel(self.widget_15)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_exposure.setFont(font)
        self.label_exposure.setStyleSheet("QLabel{\n"
"    color:rgb(255, 255, 255);\n"
"}")
        self.label_exposure.setObjectName("label_exposure")
        self.horizontalLayout_29.addWidget(self.label_exposure)
        self.horizontalLayout_29.setStretch(0, 1)
        self.horizontalLayout_29.setStretch(1, 5)
        self.horizontalLayout_29.setStretch(2, 1)
        self.verticalLayout_14.addLayout(self.horizontalLayout_29)
        self.horizontalSlider_exposure = QtWidgets.QSlider(self.widget_15)
        self.horizontalSlider_exposure.setStyleSheet("")
        self.horizontalSlider_exposure.setMinimum(-100)
        self.horizontalSlider_exposure.setMaximum(100)
        self.horizontalSlider_exposure.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_exposure.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_exposure.setObjectName("horizontalSlider_exposure")
        self.verticalLayout_14.addWidget(self.horizontalSlider_exposure)
        self.verticalLayout_15.addWidget(self.widget_15)
        self.widget_14 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_14.setMinimumSize(QtCore.QSize(0, 88))
        self.widget_14.setMaximumSize(QtCore.QSize(16777215, 88))
        self.widget_14.setObjectName("widget_14")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_14)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_image_contrast = QtWidgets.QLabel(self.widget_14)
        self.label_image_contrast.setMinimumSize(QtCore.QSize(30, 30))
        self.label_image_contrast.setStyleSheet("image:url(:/images/icon/contrast_brightness_setting_icon.svg)")
        self.label_image_contrast.setText("")
        self.label_image_contrast.setObjectName("label_image_contrast")
        self.horizontalLayout_28.addWidget(self.label_image_contrast)
        self.label_text_contrast = QtWidgets.QLabel(self.widget_14)
        self.label_text_contrast.setMinimumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_text_contrast.setFont(font)
        self.label_text_contrast.setStyleSheet("QLabel{\n"
"    color:rgb(255, 255, 255);\n"
"}")
        self.label_text_contrast.setObjectName("label_text_contrast")
        self.horizontalLayout_28.addWidget(self.label_text_contrast)
        self.label_contrast = QtWidgets.QLabel(self.widget_14)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_contrast.setFont(font)
        self.label_contrast.setStyleSheet("QLabel{\n"
"    color:rgb(255, 255, 255);\n"
"}")
        self.label_contrast.setObjectName("label_contrast")
        self.horizontalLayout_28.addWidget(self.label_contrast)
        self.horizontalLayout_28.setStretch(0, 1)
        self.horizontalLayout_28.setStretch(1, 5)
        self.horizontalLayout_28.setStretch(2, 1)
        self.verticalLayout_13.addLayout(self.horizontalLayout_28)
        self.horizontalSlider_contrast = QtWidgets.QSlider(self.widget_14)
        self.horizontalSlider_contrast.setStyleSheet("")
        self.horizontalSlider_contrast.setMinimum(-100)
        self.horizontalSlider_contrast.setMaximum(100)
        self.horizontalSlider_contrast.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_contrast.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_contrast.setObjectName("horizontalSlider_contrast")
        self.verticalLayout_13.addWidget(self.horizontalSlider_contrast)
        self.verticalLayout_15.addWidget(self.widget_14)
        self.widget_13 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_13.setMinimumSize(QtCore.QSize(0, 88))
        self.widget_13.setMaximumSize(QtCore.QSize(16777215, 88))
        self.widget_13.setObjectName("widget_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_13)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_image_saturation = QtWidgets.QLabel(self.widget_13)
        self.label_image_saturation.setMinimumSize(QtCore.QSize(30, 30))
        self.label_image_saturation.setStyleSheet("image:url(:/images/icon/bx_tone_icon.svg)")
        self.label_image_saturation.setText("")
        self.label_image_saturation.setObjectName("label_image_saturation")
        self.horizontalLayout_27.addWidget(self.label_image_saturation)
        self.label_text_saturation = QtWidgets.QLabel(self.widget_13)
        self.label_text_saturation.setMinimumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_text_saturation.setFont(font)
        self.label_text_saturation.setStyleSheet("QLabel{\n"
"    color:rgb(255, 255, 255);\n"
"}")
        self.label_text_saturation.setObjectName("label_text_saturation")
        self.horizontalLayout_27.addWidget(self.label_text_saturation)
        self.label_saturation = QtWidgets.QLabel(self.widget_13)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_saturation.setFont(font)
        self.label_saturation.setStyleSheet("QLabel{\n"
"    color:rgb(255, 255, 255);\n"
"}")
        self.label_saturation.setObjectName("label_saturation")
        self.horizontalLayout_27.addWidget(self.label_saturation)
        self.horizontalLayout_27.setStretch(0, 1)
        self.horizontalLayout_27.setStretch(1, 5)
        self.horizontalLayout_27.setStretch(2, 1)
        self.verticalLayout_12.addLayout(self.horizontalLayout_27)
        self.horizontalSlider_saturation = QtWidgets.QSlider(self.widget_13)
        self.horizontalSlider_saturation.setStyleSheet("")
        self.horizontalSlider_saturation.setMinimum(-100)
        self.horizontalSlider_saturation.setMaximum(100)
        self.horizontalSlider_saturation.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_saturation.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_saturation.setObjectName("horizontalSlider_saturation")
        self.verticalLayout_12.addWidget(self.horizontalSlider_saturation)
        self.verticalLayout_15.addWidget(self.widget_13)
        self.widget_12 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_12.setMinimumSize(QtCore.QSize(0, 88))
        self.widget_12.setMaximumSize(QtCore.QSize(16777215, 88))
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_12)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_image_sharp = QtWidgets.QLabel(self.widget_12)
        self.label_image_sharp.setMinimumSize(QtCore.QSize(30, 30))
        self.label_image_sharp.setStyleSheet("image:url(:/images/icon/triangle_outline_icon.svg)")
        self.label_image_sharp.setText("")
        self.label_image_sharp.setObjectName("label_image_sharp")
        self.horizontalLayout_26.addWidget(self.label_image_sharp)
        self.label_text_sharp = QtWidgets.QLabel(self.widget_12)
        self.label_text_sharp.setMinimumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_text_sharp.setFont(font)
        self.label_text_sharp.setStyleSheet("QLabel{\n"
"    color:rgb(255, 255, 255);\n"
"}")
        self.label_text_sharp.setObjectName("label_text_sharp")
        self.horizontalLayout_26.addWidget(self.label_text_sharp)
        self.label_sharp = QtWidgets.QLabel(self.widget_12)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_sharp.setFont(font)
        self.label_sharp.setStyleSheet("QLabel{\n"
"    color:rgb(255, 255, 255);\n"
"}")
        self.label_sharp.setObjectName("label_sharp")
        self.horizontalLayout_26.addWidget(self.label_sharp)
        self.horizontalLayout_26.setStretch(0, 1)
        self.horizontalLayout_26.setStretch(1, 5)
        self.horizontalLayout_26.setStretch(2, 1)
        self.verticalLayout_11.addLayout(self.horizontalLayout_26)
        self.horizontalSlider_sharp = QtWidgets.QSlider(self.widget_12)
        self.horizontalSlider_sharp.setStyleSheet("")
        self.horizontalSlider_sharp.setMinimum(-100)
        self.horizontalSlider_sharp.setMaximum(100)
        self.horizontalSlider_sharp.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_sharp.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_sharp.setObjectName("horizontalSlider_sharp")
        self.verticalLayout_11.addWidget(self.horizontalSlider_sharp)
        self.verticalLayout_15.addWidget(self.widget_12)
        self.widget_11 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_11.setMinimumSize(QtCore.QSize(0, 88))
        self.widget_11.setMaximumSize(QtCore.QSize(16777215, 88))
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_image_smooth = QtWidgets.QLabel(self.widget_11)
        self.label_image_smooth.setMinimumSize(QtCore.QSize(30, 30))
        self.label_image_smooth.setStyleSheet("image:url(:/images/icon/curve_auto_colon_icon.svg)")
        self.label_image_smooth.setText("")
        self.label_image_smooth.setObjectName("label_image_smooth")
        self.horizontalLayout_25.addWidget(self.label_image_smooth)
        self.label_text_smooth = QtWidgets.QLabel(self.widget_11)
        self.label_text_smooth.setMinimumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_text_smooth.setFont(font)
        self.label_text_smooth.setStyleSheet("QLabel{\n"
"    color:rgb(255, 255, 255);\n"
"}")
        self.label_text_smooth.setObjectName("label_text_smooth")
        self.horizontalLayout_25.addWidget(self.label_text_smooth)
        self.label_smooth = QtWidgets.QLabel(self.widget_11)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_smooth.setFont(font)
        self.label_smooth.setStyleSheet("QLabel{\n"
"    color:rgb(255, 255, 255);\n"
"}")
        self.label_smooth.setObjectName("label_smooth")
        self.horizontalLayout_25.addWidget(self.label_smooth)
        self.horizontalLayout_25.setStretch(0, 1)
        self.horizontalLayout_25.setStretch(1, 5)
        self.horizontalLayout_25.setStretch(2, 1)
        self.verticalLayout_10.addLayout(self.horizontalLayout_25)
        self.horizontalSlider_smooth = QtWidgets.QSlider(self.widget_11)
        self.horizontalSlider_smooth.setStyleSheet("")
        self.horizontalSlider_smooth.setMinimum(-100)
        self.horizontalSlider_smooth.setMaximum(100)
        self.horizontalSlider_smooth.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_smooth.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_smooth.setObjectName("horizontalSlider_smooth")
        self.verticalLayout_10.addWidget(self.horizontalSlider_smooth)
        self.verticalLayout_15.addWidget(self.widget_11)
        self.widget_10 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_10.setMinimumSize(QtCore.QSize(0, 88))
        self.widget_10.setMaximumSize(QtCore.QSize(16777215, 88))
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_image_temperature = QtWidgets.QLabel(self.widget_10)
        self.label_image_temperature.setMinimumSize(QtCore.QSize(30, 30))
        self.label_image_temperature.setStyleSheet("image:url(:/images/icon/thermometer_high_icon.svg)")
        self.label_image_temperature.setText("")
        self.label_image_temperature.setObjectName("label_image_temperature")
        self.horizontalLayout_24.addWidget(self.label_image_temperature)
        self.label_text_temperature = QtWidgets.QLabel(self.widget_10)
        self.label_text_temperature.setMinimumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_text_temperature.setFont(font)
        self.label_text_temperature.setStyleSheet("QLabel{\n"
"    color:rgb(255, 255, 255);\n"
"}")
        self.label_text_temperature.setObjectName("label_text_temperature")
        self.horizontalLayout_24.addWidget(self.label_text_temperature)
        self.label_temperature = QtWidgets.QLabel(self.widget_10)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_temperature.setFont(font)
        self.label_temperature.setStyleSheet("QLabel{\n"
"    color:rgb(255, 255, 255);\n"
"}")
        self.label_temperature.setObjectName("label_temperature")
        self.horizontalLayout_24.addWidget(self.label_temperature)
        self.horizontalLayout_24.setStretch(0, 1)
        self.horizontalLayout_24.setStretch(1, 5)
        self.horizontalLayout_24.setStretch(2, 1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_24)
        self.horizontalSlider_temperature = QtWidgets.QSlider(self.widget_10)
        self.horizontalSlider_temperature.setStyleSheet("")
        self.horizontalSlider_temperature.setMinimum(-100)
        self.horizontalSlider_temperature.setMaximum(100)
        self.horizontalSlider_temperature.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_temperature.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_temperature.setObjectName("horizontalSlider_temperature")
        self.verticalLayout_9.addWidget(self.horizontalSlider_temperature)
        self.verticalLayout_15.addWidget(self.widget_10)
        self.widget_9 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_9.setMinimumSize(QtCore.QSize(0, 88))
        self.widget_9.setMaximumSize(QtCore.QSize(16777215, 88))
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_image_tone = QtWidgets.QLabel(self.widget_9)
        self.label_image_tone.setMinimumSize(QtCore.QSize(30, 30))
        self.label_image_tone.setStyleSheet("image:url(:/images/icon/bx_color_fill_icon.svg)")
        self.label_image_tone.setText("")
        self.label_image_tone.setObjectName("label_image_tone")
        self.horizontalLayout_23.addWidget(self.label_image_tone)
        self.label_text_tone = QtWidgets.QLabel(self.widget_9)
        self.label_text_tone.setMinimumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_text_tone.setFont(font)
        self.label_text_tone.setStyleSheet("QLabel{\n"
"    color:rgb(255, 255, 255);\n"
"}")
        self.label_text_tone.setObjectName("label_text_tone")
        self.horizontalLayout_23.addWidget(self.label_text_tone)
        self.label_tone = QtWidgets.QLabel(self.widget_9)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_tone.setFont(font)
        self.label_tone.setStyleSheet("QLabel{\n"
"    color:rgb(255, 255, 255);\n"
"}")
        self.label_tone.setObjectName("label_tone")
        self.horizontalLayout_23.addWidget(self.label_tone)
        self.horizontalLayout_23.setStretch(0, 1)
        self.horizontalLayout_23.setStretch(1, 5)
        self.horizontalLayout_23.setStretch(2, 1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_23)
        self.horizontalSlider_tone = QtWidgets.QSlider(self.widget_9)
        self.horizontalSlider_tone.setStyleSheet("")
        self.horizontalSlider_tone.setMinimum(-100)
        self.horizontalSlider_tone.setMaximum(100)
        self.horizontalSlider_tone.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_tone.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_tone.setObjectName("horizontalSlider_tone")
        self.verticalLayout_8.addWidget(self.horizontalSlider_tone)
        self.verticalLayout_15.addWidget(self.widget_9)
        self.widget_8 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_8.setMinimumSize(QtCore.QSize(0, 88))
        self.widget_8.setMaximumSize(QtCore.QSize(16777215, 88))
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_10 = QtWidgets.QLabel(self.widget_8)
        self.label_10.setMinimumSize(QtCore.QSize(30, 30))
        self.label_10.setStyleSheet("image:url(:/images/icon/bright_light_control_shine_icon.svg)")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_22.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.widget_8)
        self.label_11.setMinimumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("QLabel{\n"
"    color:rgb(255, 255, 255);\n"
"}")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_22.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.widget_8)
        self.label_12.setMinimumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("QLabel{\n"
"    color:rgb(255, 255, 255);\n"
"}")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_22.addWidget(self.label_12)
        self.horizontalLayout_22.setStretch(0, 1)
        self.horizontalLayout_22.setStretch(1, 5)
        self.horizontalLayout_22.setStretch(2, 1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_22)
        self.horizontalSlider_6 = QtWidgets.QSlider(self.widget_8)
        self.horizontalSlider_6.setStyleSheet("")
        self.horizontalSlider_6.setMinimum(-100)
        self.horizontalSlider_6.setMaximum(100)
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_6.setObjectName("horizontalSlider_6")
        self.verticalLayout_7.addWidget(self.horizontalSlider_6)
        self.verticalLayout_15.addWidget(self.widget_8)
        self.widget_7 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_7.setMinimumSize(QtCore.QSize(0, 88))
        self.widget_7.setMaximumSize(QtCore.QSize(16777215, 88))
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_7 = QtWidgets.QLabel(self.widget_7)
        self.label_7.setMinimumSize(QtCore.QSize(30, 30))
        self.label_7.setStyleSheet("image:url(:/images/icon/bright_light_control_shine_icon.svg)")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_21.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.widget_7)
        self.label_8.setMinimumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("QLabel{\n"
"    color:rgb(255, 255, 255);\n"
"}")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_21.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.widget_7)
        self.label_9.setMinimumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel{\n"
"    color:rgb(255, 255, 255);\n"
"}")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_21.addWidget(self.label_9)
        self.horizontalLayout_21.setStretch(0, 1)
        self.horizontalLayout_21.setStretch(1, 5)
        self.horizontalLayout_21.setStretch(2, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_21)
        self.horizontalSlider_5 = QtWidgets.QSlider(self.widget_7)
        self.horizontalSlider_5.setStyleSheet("")
        self.horizontalSlider_5.setMinimum(-100)
        self.horizontalSlider_5.setMaximum(100)
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_5.setObjectName("horizontalSlider_5")
        self.verticalLayout_6.addWidget(self.horizontalSlider_5)
        self.verticalLayout_15.addWidget(self.widget_7)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_18.addWidget(self.scrollArea)
        self.horizontalLayout_17.addWidget(self.widget_adjust)
        self.horizontalLayout_17.setStretch(0, 2)
        self.horizontalLayout_17.setStretch(1, 1)
        self.main_stacked_widget.addWidget(self.page_adjust_function)
        self.horizontalLayout_8.addWidget(self.main_stacked_widget)
        self.verticalLayout.addWidget(self.widget_view)
        self.frame_function = QtWidgets.QFrame(self.frame)
        self.frame_function.setMinimumSize(QtCore.QSize(0, 84))
        self.frame_function.setStyleSheet(".QFrame#frame_function{\n"
"    background-color: rgb(32, 32, 32);\n"
"}")
        self.frame_function.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_function.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_function.setObjectName("frame_function")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_function)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_undo = QtWidgets.QPushButton(self.frame_function)
        self.pushButton_undo.setMinimumSize(QtCore.QSize(61, 61))
        self.pushButton_undo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_undo.setToolTipDuration(3000)
        self.pushButton_undo.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_undo.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/images/icon/undo_line_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_undo.setIcon(icon11)
        self.pushButton_undo.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_undo.setFlat(True)
        self.pushButton_undo.setObjectName("pushButton_undo")
        self.horizontalLayout_4.addWidget(self.pushButton_undo)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.pushButton_redo = QtWidgets.QPushButton(self.frame_function)
        self.pushButton_redo.setMinimumSize(QtCore.QSize(61, 61))
        self.pushButton_redo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_redo.setToolTipDuration(3000)
        self.pushButton_redo.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_redo.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/images/icon/redo_line_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_redo.setIcon(icon12)
        self.pushButton_redo.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_redo.setFlat(True)
        self.pushButton_redo.setObjectName("pushButton_redo")
        self.horizontalLayout_4.addWidget(self.pushButton_redo)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.pushButton_reset = QtWidgets.QPushButton(self.frame_function)
        self.pushButton_reset.setMinimumSize(QtCore.QSize(61, 61))
        self.pushButton_reset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_reset.setToolTipDuration(3000)
        self.pushButton_reset.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_reset.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/images/icon/circulate_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_reset.setIcon(icon13)
        self.pushButton_reset.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_reset.setFlat(True)
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.horizontalLayout_4.addWidget(self.pushButton_reset)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_4)
        self.separator = QtWidgets.QWidget(self.frame_function)
        self.separator.setMinimumSize(QtCore.QSize(60, 65))
        self.separator.setStyleSheet("image:url(:/images/icon/vertical_line_icon.svg);\n"
"background-color: transparent;")
        self.separator.setObjectName("separator")
        self.horizontalLayout_7.addWidget(self.separator)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_crop = QtWidgets.QPushButton(self.frame_function)
        self.pushButton_crop.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_crop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_crop.setToolTipDuration(3000)
        self.pushButton_crop.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_crop.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/images/icon/crop_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_crop.setIcon(icon14)
        self.pushButton_crop.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_crop.setFlat(True)
        self.pushButton_crop.setObjectName("pushButton_crop")
        self.horizontalLayout_6.addWidget(self.pushButton_crop)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.pushButton_rotate = QtWidgets.QPushButton(self.frame_function)
        self.pushButton_rotate.setMinimumSize(QtCore.QSize(61, 57))
        self.pushButton_rotate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_rotate.setToolTipDuration(3000)
        self.pushButton_rotate.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_rotate.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/images/icon/rotate_cw_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_rotate.setIcon(icon15)
        self.pushButton_rotate.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_rotate.setFlat(True)
        self.pushButton_rotate.setObjectName("pushButton_rotate")
        self.horizontalLayout_6.addWidget(self.pushButton_rotate)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.pushButton_curve = QtWidgets.QPushButton(self.frame_function)
        self.pushButton_curve.setMinimumSize(QtCore.QSize(61, 57))
        self.pushButton_curve.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_curve.setToolTipDuration(3000)
        self.pushButton_curve.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_curve.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/images/icon/curve_adjustment_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_curve.setIcon(icon16)
        self.pushButton_curve.setIconSize(QtCore.QSize(43, 43))
        self.pushButton_curve.setFlat(True)
        self.pushButton_curve.setObjectName("pushButton_curve")
        self.horizontalLayout_6.addWidget(self.pushButton_curve)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.pushButton_face = QtWidgets.QPushButton(self.frame_function)
        self.pushButton_face.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_face.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_face.setToolTipDuration(3000)
        self.pushButton_face.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_face.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/images/icon/face_smile_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_face.setIcon(icon17)
        self.pushButton_face.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_face.setFlat(True)
        self.pushButton_face.setObjectName("pushButton_face")
        self.horizontalLayout_6.addWidget(self.pushButton_face)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.pushButton_text = QtWidgets.QPushButton(self.frame_function)
        self.pushButton_text.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_text.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_text.setToolTipDuration(3000)
        self.pushButton_text.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_text.setText("")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/images/icon/type_text_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_text.setIcon(icon18)
        self.pushButton_text.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_text.setFlat(True)
        self.pushButton_text.setObjectName("pushButton_text")
        self.horizontalLayout_6.addWidget(self.pushButton_text)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem12)
        self.pushButton_adjust = QtWidgets.QPushButton(self.frame_function)
        self.pushButton_adjust.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_adjust.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_adjust.setToolTipDuration(3000)
        self.pushButton_adjust.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_adjust.setText("")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/images/icon/adjust_control_con.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_adjust.setIcon(icon19)
        self.pushButton_adjust.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_adjust.setFlat(True)
        self.pushButton_adjust.setObjectName("pushButton_adjust")
        self.horizontalLayout_6.addWidget(self.pushButton_adjust)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7.setStretch(0, 4)
        self.horizontalLayout_7.setStretch(1, 1)
        self.horizontalLayout_7.setStretch(2, 12)
        self.verticalLayout.addWidget(self.frame_function)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 15)
        self.verticalLayout.setStretch(2, 2)
        self.horizontalLayout_5.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.main_stacked_widget.setCurrentIndex(0)
        self.basic_function_stack.setCurrentIndex(0)
        self.horizontalSlider_light_perception.valueChanged['int'].connect(self.label_light_perception.setNum) # type: ignore
        self.horizontalSlider_brightness.valueChanged['int'].connect(self.label_brightness.setNum) # type: ignore
        self.horizontalSlider_exposure.valueChanged['int'].connect(self.label_exposure.setNum) # type: ignore
        self.horizontalSlider_contrast.valueChanged['int'].connect(self.label_contrast.setNum) # type: ignore
        self.horizontalSlider_saturation.valueChanged['int'].connect(self.label_saturation.setNum) # type: ignore
        self.horizontalSlider_sharp.valueChanged['int'].connect(self.label_sharp.setNum) # type: ignore
        self.horizontalSlider_smooth.valueChanged['int'].connect(self.label_smooth.setNum) # type: ignore
        self.horizontalSlider_temperature.valueChanged['int'].connect(self.label_temperature.setNum) # type: ignore
        self.horizontalSlider_tone.valueChanged['int'].connect(self.label_tone.setNum) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_logo.setText(_translate("MainWindow", "image-editor"))
        self.pushButton_min_2.setToolTip(_translate("MainWindow", "放大"))
        self.pushButton_min_3.setToolTip(_translate("MainWindow", "缩小"))
        self.pushButton_min.setToolTip(_translate("MainWindow", "最小化"))
        self.pushButton_max.setToolTip(_translate("MainWindow", "最大化"))
        self.pushButton_close.setToolTip(_translate("MainWindow", "关闭"))
        self.pushButton_min_4.setToolTip(_translate("MainWindow", "应用"))
        self.pushButton_min_5.setToolTip(_translate("MainWindow", "取消"))
        self.pushButton_left_90.setToolTip(_translate("MainWindow", "逆时针旋转90°"))
        self.pushButton_right_90.setToolTip(_translate("MainWindow", "顺时针旋转90°"))
        self.pushButton_flip_y.setToolTip(_translate("MainWindow", "X镜像"))
        self.pushButton_flip_x.setToolTip(_translate("MainWindow", "Y镜像"))
        self.label_text_light.setText(_translate("MainWindow", "光感"))
        self.label_light_perception.setText(_translate("MainWindow", "0"))
        self.label_text_brightness.setText(_translate("MainWindow", "亮度"))
        self.label_brightness.setText(_translate("MainWindow", "0"))
        self.label_text_exposure.setText(_translate("MainWindow", "曝光"))
        self.label_exposure.setText(_translate("MainWindow", "0"))
        self.label_text_contrast.setText(_translate("MainWindow", "对比度"))
        self.label_contrast.setText(_translate("MainWindow", "0"))
        self.label_text_saturation.setText(_translate("MainWindow", "饱和度"))
        self.label_saturation.setText(_translate("MainWindow", "0"))
        self.label_text_sharp.setText(_translate("MainWindow", "锐化"))
        self.label_sharp.setText(_translate("MainWindow", "0"))
        self.label_text_smooth.setText(_translate("MainWindow", "平滑"))
        self.label_smooth.setText(_translate("MainWindow", "0"))
        self.label_text_temperature.setText(_translate("MainWindow", "色温"))
        self.label_temperature.setText(_translate("MainWindow", "0"))
        self.label_text_tone.setText(_translate("MainWindow", "色调"))
        self.label_tone.setText(_translate("MainWindow", "0"))
        self.label_11.setText(_translate("MainWindow", "光感"))
        self.label_12.setText(_translate("MainWindow", "-100"))
        self.label_8.setText(_translate("MainWindow", "光感"))
        self.label_9.setText(_translate("MainWindow", "-100"))
        self.pushButton_undo.setToolTip(_translate("MainWindow", "撤销"))
        self.pushButton_redo.setToolTip(_translate("MainWindow", "恢复"))
        self.pushButton_reset.setToolTip(_translate("MainWindow", "重置"))
        self.pushButton_crop.setToolTip(_translate("MainWindow", "裁剪"))
        self.pushButton_rotate.setToolTip(_translate("MainWindow", "旋转"))
        self.pushButton_curve.setToolTip(_translate("MainWindow", "曲线调色"))
        self.pushButton_face.setToolTip(_translate("MainWindow", "人脸"))
        self.pushButton_text.setToolTip(_translate("MainWindow", "文字"))
        self.pushButton_adjust.setToolTip(_translate("MainWindow", "调节"))
import resources_rc
