# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1020, 680)
        MainWindow.setMinimumSize(QtCore.QSize(1020, 680))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMouseTracking(True)
        self.centralwidget.setAcceptDrops(True)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: rgba(112, 112, 112, 255);\n"
"    border:none;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_menu = QtWidgets.QFrame(self.frame)
        self.frame_menu.setStyleSheet(".QFrame#frame_menu{\n"
"    background-color:rgb(32, 32, 32);\n"
"}")
        self.frame_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu.setObjectName("frame_menu")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_menu)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.frame_menu)
        self.widget.setMinimumSize(QtCore.QSize(40, 0))
        self.widget.setStyleSheet("image:url(:/images/icon/image_photo_picture_gallery_icon.png)")
        self.widget.setObjectName("widget")
        self.horizontalLayout.addWidget(self.widget)
        self.label = QtWidgets.QLabel(self.frame_menu)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"    background-color:transparent;\n"
"    color:rgb(255, 255, 255);\n"
"}")
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.horizontalLayout_10.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_min_2 = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_min_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_min_2.setToolTipDuration(3000)
        self.pushButton_min_2.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_min_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icon/zoom_in_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_min_2.setIcon(icon)
        self.pushButton_min_2.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_min_2.setFlat(True)
        self.pushButton_min_2.setObjectName("pushButton_min_2")
        self.horizontalLayout_3.addWidget(self.pushButton_min_2)
        self.pushButton_min_3 = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_min_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_min_3.setToolTipDuration(3000)
        self.pushButton_min_3.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_min_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/icon/zoom_out_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_min_3.setIcon(icon1)
        self.pushButton_min_3.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_min_3.setFlat(True)
        self.pushButton_min_3.setObjectName("pushButton_min_3")
        self.horizontalLayout_3.addWidget(self.pushButton_min_3)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_min = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_min.setToolTipDuration(3000)
        self.pushButton_min.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}\n"
".QPushButton:pressed{\n"
"    background-color:rgb(90, 90, 90);\n"
"    border-radius:10px;\n"
"}\n"
".QPushButton:normal{\n"
"    background-color:transparent;\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_min.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/icon/minus_delete_remove_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_min.setIcon(icon2)
        self.pushButton_min.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_min.setDefault(False)
        self.pushButton_min.setFlat(True)
        self.pushButton_min.setObjectName("pushButton_min")
        self.horizontalLayout_2.addWidget(self.pushButton_min)
        self.pushButton_max = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_max.setToolTipDuration(3000)
        self.pushButton_max.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}\n"
".QPushButton:pressed{\n"
"    background-color:rgb(90, 90, 90);\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_max.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/icon/maximize_expand_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/images/icon/minimize_2_reduce_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_max.setIcon(icon3)
        self.pushButton_max.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_max.setFlat(True)
        self.pushButton_max.setObjectName("pushButton_max")
        self.horizontalLayout_2.addWidget(self.pushButton_max)
        self.pushButton_close = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_close.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_close.setToolTipDuration(3000)
        self.pushButton_close.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(255, 0, 0);\n"
"    border-radius:10px;\n"
"}\n"
".QPushButton:pressed{\n"
"    background-color:rgba(255, 0, 0, 190);\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_close.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/icon/power_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_close.setIcon(icon4)
        self.pushButton_close.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_close.setFlat(True)
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout_2.addWidget(self.pushButton_close)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.frame_menu)
        self.frame_view = QtWidgets.QFrame(self.frame)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.frame_view.setFont(font)
        self.frame_view.setStyleSheet("QFrame{\n"
"    background-color: rgba(112, 112, 112, 255);\n"
"    border:none;\n"
"}")
        self.frame_view.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_view.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_view.setObjectName("frame_view")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_view)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.loadWidget = QtWidgets.QWidget(self.frame_view)
        self.loadWidget.setMinimumSize(QtCore.QSize(550, 300))
        self.loadWidget.setMaximumSize(QtCore.QSize(550, 300))
        self.loadWidget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loadWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.loadWidget.setStyleSheet(".QWidget#loadWidget{\n"
"    border: 5px dashed #ccc;\n"
"    border-radius:10px;\n"
"    background-color:transparent;\n"
"}\n"
".QWidget#loadWidget:hover{\n"
"    background-color: rgba(0, 170, 255, 50);\n"
"}")
        self.loadWidget.setObjectName("loadWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.loadWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.widget_2 = QtWidgets.QWidget(self.loadWidget)
        self.widget_2.setMinimumSize(QtCore.QSize(161, 141))
        self.widget_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.widget_2.setStyleSheet("QWidget{\n"
"    image:url(:/images/icon/download_cloud_multimedia_icon.svg);\n"
"    background-color: transparent;\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2.addWidget(self.widget_2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.label_2 = QtWidgets.QLabel(self.loadWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("QLabel{\n"
"    background-color:transparent;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_8.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.loadWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel{\n"
"    background-color:transparent;\n"
"    color: rgb(64, 158, 255);\n"
"}")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_8.addWidget(self.label_3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.horizontalLayout_9.addWidget(self.loadWidget)
        self.verticalLayout.addWidget(self.frame_view)
        self.frame_function = QtWidgets.QFrame(self.frame)
        self.frame_function.setMinimumSize(QtCore.QSize(0, 84))
        self.frame_function.setStyleSheet(".QFrame#frame_function{\n"
"    background-color: rgb(32, 32, 32);\n"
"}")
        self.frame_function.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_function.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_function.setObjectName("frame_function")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_function)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_undo = QtWidgets.QPushButton(self.frame_function)
        self.pushButton_undo.setMinimumSize(QtCore.QSize(61, 61))
        self.pushButton_undo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_undo.setToolTipDuration(3000)
        self.pushButton_undo.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_undo.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/icon/undo_line_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_undo.setIcon(icon5)
        self.pushButton_undo.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_undo.setFlat(True)
        self.pushButton_undo.setObjectName("pushButton_undo")
        self.horizontalLayout_4.addWidget(self.pushButton_undo)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.pushButton_redo = QtWidgets.QPushButton(self.frame_function)
        self.pushButton_redo.setMinimumSize(QtCore.QSize(61, 61))
        self.pushButton_redo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_redo.setToolTipDuration(3000)
        self.pushButton_redo.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_redo.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/icon/redo_line_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_redo.setIcon(icon6)
        self.pushButton_redo.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_redo.setFlat(True)
        self.pushButton_redo.setObjectName("pushButton_redo")
        self.horizontalLayout_4.addWidget(self.pushButton_redo)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.pushButton_reset = QtWidgets.QPushButton(self.frame_function)
        self.pushButton_reset.setMinimumSize(QtCore.QSize(61, 61))
        self.pushButton_reset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_reset.setToolTipDuration(3000)
        self.pushButton_reset.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_reset.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/icon/circulate_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_reset.setIcon(icon7)
        self.pushButton_reset.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_reset.setFlat(True)
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.horizontalLayout_4.addWidget(self.pushButton_reset)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_4)
        self.widget_3 = QtWidgets.QWidget(self.frame_function)
        self.widget_3.setMinimumSize(QtCore.QSize(60, 65))
        self.widget_3.setStyleSheet("image:url(:/images/icon/vertical_line_icon.svg);\n"
"background-color: transparent;")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_7.addWidget(self.widget_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_crop = QtWidgets.QPushButton(self.frame_function)
        self.pushButton_crop.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_crop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_crop.setToolTipDuration(3000)
        self.pushButton_crop.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_crop.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/icon/crop_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_crop.setIcon(icon8)
        self.pushButton_crop.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_crop.setFlat(True)
        self.pushButton_crop.setObjectName("pushButton_crop")
        self.horizontalLayout_6.addWidget(self.pushButton_crop)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_function)
        self.pushButton_12.setMinimumSize(QtCore.QSize(61, 57))
        self.pushButton_12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_12.setToolTipDuration(3000)
        self.pushButton_12.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_12.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/images/icon/rotate_cw_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon9)
        self.pushButton_12.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_12.setFlat(True)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_6.addWidget(self.pushButton_12)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_function)
        self.pushButton_10.setMinimumSize(QtCore.QSize(61, 57))
        self.pushButton_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_10.setToolTipDuration(3000)
        self.pushButton_10.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_10.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/images/icon/curve_adjustment_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon10)
        self.pushButton_10.setIconSize(QtCore.QSize(43, 43))
        self.pushButton_10.setFlat(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_6.addWidget(self.pushButton_10)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.pushButton_face = QtWidgets.QPushButton(self.frame_function)
        self.pushButton_face.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_face.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_face.setToolTipDuration(3000)
        self.pushButton_face.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_face.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/images/icon/face_smile_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_face.setIcon(icon11)
        self.pushButton_face.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_face.setFlat(True)
        self.pushButton_face.setObjectName("pushButton_face")
        self.horizontalLayout_6.addWidget(self.pushButton_face)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.pushButton_text = QtWidgets.QPushButton(self.frame_function)
        self.pushButton_text.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_text.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_text.setToolTipDuration(3000)
        self.pushButton_text.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_text.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/images/icon/type_text_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_text.setIcon(icon12)
        self.pushButton_text.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_text.setFlat(True)
        self.pushButton_text.setObjectName("pushButton_text")
        self.horizontalLayout_6.addWidget(self.pushButton_text)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem12)
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_function)
        self.pushButton_11.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_11.setToolTipDuration(3000)
        self.pushButton_11.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_11.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/images/icon/adjust_control_con.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon13)
        self.pushButton_11.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_11.setFlat(True)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_6.addWidget(self.pushButton_11)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7.setStretch(0, 4)
        self.horizontalLayout_7.setStretch(1, 1)
        self.horizontalLayout_7.setStretch(2, 12)
        self.verticalLayout.addWidget(self.frame_function)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 15)
        self.verticalLayout.setStretch(2, 2)
        self.horizontalLayout_5.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "image-editor"))
        self.pushButton_min_2.setToolTip(_translate("MainWindow", "放大"))
        self.pushButton_min_3.setToolTip(_translate("MainWindow", "缩小"))
        self.pushButton_min.setToolTip(_translate("MainWindow", "最小化"))
        self.pushButton_max.setToolTip(_translate("MainWindow", "最大化"))
        self.pushButton_close.setToolTip(_translate("MainWindow", "关闭"))
        self.label_2.setText(_translate("MainWindow", "将图片拖拽到此处，或"))
        self.label_3.setText(_translate("MainWindow", "点击上传"))
        self.pushButton_undo.setToolTip(_translate("MainWindow", "撤销"))
        self.pushButton_redo.setToolTip(_translate("MainWindow", "恢复"))
        self.pushButton_reset.setToolTip(_translate("MainWindow", "重置"))
        self.pushButton_crop.setToolTip(_translate("MainWindow", "裁剪"))
        self.pushButton_12.setToolTip(_translate("MainWindow", "旋转"))
        self.pushButton_10.setToolTip(_translate("MainWindow", "曲线调色"))
        self.pushButton_face.setToolTip(_translate("MainWindow", "人脸"))
        self.pushButton_text.setToolTip(_translate("MainWindow", "文字"))
        self.pushButton_11.setToolTip(_translate("MainWindow", "调节"))
import resources_rc
