# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_xml/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1020, 680)
        MainWindow.setMinimumSize(QtCore.QSize(1020, 680))
        MainWindow.setStyleSheet("QScrollBar:horizontal{\n"
"    height:8px;\n"
"    background:rgba(0,0,0,0%);\n"
"border-radius:4px;\n"
"\n"
"}\n"
"QScrollBar::handle:horizontal{\n"
"    background:rgba(255,255,255,50%);\n"
"border-radius:4px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover{\n"
"    background:rgba(255,255,255,100%);\n"
"    min-width:0;\n"
"}\n"
"QScrollBar::add-line:horizontal{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::sub-line:horizontal{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::add-line:horizontal:hover{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::add-page:horizontal,QScrollBar::sub-page:horizontal\n"
"{\n"
"    background:rgba(0,0,0,10%);\n"
"    border-radius:4px;\n"
"}\n"
"\n"
"QScrollBar:vertical{\n"
"    width:8px;\n"
"    background:rgba(0,0,0,0%);\n"
"\n"
"}\n"
"QScrollBar::handle:vertical{\n"
"    width:0px;\n"
"    background:rgba(255,255,255,50%);\n"
"    border-radius:4px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{\n"
"    width:0px;\n"
"    background:rgba(255,255,255,100%);\n"
"    border-radius:4px;\n"
"    min-width:20;\n"
"}\n"
"QScrollBar::add-line:vertical{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::sub-line:vertical{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::add-line:vertical:hover{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::sub-line:vertical:hover{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::add-page:vertical,QScrollBar::sub-page:vertical\n"
"{\n"
"    background:rgba(0,0,0,10%);\n"
"    border-radius:4px;\n"
"}\n"
"\n"
" \n"
" \n"
"QSlider::add-page:horizontal {\n"
"    background-color: qlineargradient(spread: pad, x1: 0, y1: 1, x2: 1, y2: 1,\n"
"                                      stop: 0 rgb(100, 100, 100),\n"
"                                      stop: 1 rgb(255, 78, 0,));\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background-color: qlineargradient(spread: pad, x1: 0, y1: 1, x2: 1, y2: 1,\n"
"                                      stop: 0 rgb(51, 151, 255),\n"
"                                      stop: 1 rgb(100, 100, 100));\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    background: transparent;\n"
"    height: 8px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    width: 16px;\n"
"    height: 18px;\n"
"    margin: -4px 0px -4px 0px;\n"
"    border-radius: 8px;\n"
"    background: white;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMouseTracking(True)
        self.centralwidget.setAcceptDrops(True)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: rgba(112, 112, 112, 255);\n"
"    border:none;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_menu = QtWidgets.QFrame(self.frame)
        self.frame_menu.setStyleSheet(".QFrame#frame_menu{\n"
"    background-color:rgb(32, 32, 32);\n"
"}")
        self.frame_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu.setObjectName("frame_menu")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_menu)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_logo = QtWidgets.QHBoxLayout()
        self.horizontalLayout_logo.setObjectName("horizontalLayout_logo")
        self.widget_logo = QtWidgets.QWidget(self.frame_menu)
        self.widget_logo.setMinimumSize(QtCore.QSize(40, 0))
        self.widget_logo.setStyleSheet("image:url(:/images/icon/image_photo_picture_gallery_icon.png)")
        self.widget_logo.setObjectName("widget_logo")
        self.horizontalLayout_logo.addWidget(self.widget_logo)
        self.label_logo = QtWidgets.QLabel(self.frame_menu)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_logo.setFont(font)
        self.label_logo.setStyleSheet("QLabel{\n"
"    background-color:transparent;\n"
"    color:rgb(255, 255, 255);\n"
"}")
        self.label_logo.setWordWrap(False)
        self.label_logo.setObjectName("label_logo")
        self.horizontalLayout_logo.addWidget(self.label_logo)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_logo)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.horizontalLayout_scale = QtWidgets.QHBoxLayout()
        self.horizontalLayout_scale.setObjectName("horizontalLayout_scale")
        self.pushButton_zoom_in = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_zoom_in.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_zoom_in.setToolTipDuration(3000)
        self.pushButton_zoom_in.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}\n"
".QPushButton:pressed{\n"
"    background-color:rgb(90, 90, 90);\n"
"    border-radius:10px;\n"
"}\n"
".QPushButton:normal{\n"
"    background-color:transparent;\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_zoom_in.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icon/zoom_in_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_zoom_in.setIcon(icon)
        self.pushButton_zoom_in.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_zoom_in.setFlat(True)
        self.pushButton_zoom_in.setObjectName("pushButton_zoom_in")
        self.horizontalLayout_scale.addWidget(self.pushButton_zoom_in)
        self.pushButton_zoom_out = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_zoom_out.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_zoom_out.setToolTipDuration(3000)
        self.pushButton_zoom_out.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}\n"
".QPushButton:pressed{\n"
"    background-color:rgb(90, 90, 90);\n"
"    border-radius:10px;\n"
"}\n"
".QPushButton:normal{\n"
"    background-color:transparent;\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_zoom_out.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/icon/zoom_out_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_zoom_out.setIcon(icon1)
        self.pushButton_zoom_out.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_zoom_out.setFlat(True)
        self.pushButton_zoom_out.setObjectName("pushButton_zoom_out")
        self.horizontalLayout_scale.addWidget(self.pushButton_zoom_out)
        self.label_scale = QtWidgets.QLabel(self.frame_menu)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        self.label_scale.setFont(font)
        self.label_scale.setStyleSheet("QLabel{\n"
"    background-color:transparent;\n"
"    color:rgb(255, 255, 255);\n"
"}")
        self.label_scale.setObjectName("label_scale")
        self.horizontalLayout_scale.addWidget(self.label_scale)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_scale)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.horizontalLayout_control_window = QtWidgets.QHBoxLayout()
        self.horizontalLayout_control_window.setObjectName("horizontalLayout_control_window")
        self.pushButton_min = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_min.setToolTipDuration(3000)
        self.pushButton_min.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}\n"
".QPushButton:pressed{\n"
"    background-color:rgb(90, 90, 90);\n"
"    border-radius:10px;\n"
"}\n"
".QPushButton:normal{\n"
"    background-color:transparent;\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_min.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/icon/minus_delete_remove_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_min.setIcon(icon2)
        self.pushButton_min.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_min.setDefault(False)
        self.pushButton_min.setFlat(True)
        self.pushButton_min.setObjectName("pushButton_min")
        self.horizontalLayout_control_window.addWidget(self.pushButton_min)
        self.pushButton_max_and_reduction = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_max_and_reduction.setToolTipDuration(3000)
        self.pushButton_max_and_reduction.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}\n"
".QPushButton:pressed{\n"
"    background-color:rgb(90, 90, 90);\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_max_and_reduction.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/icon/maximize_expand_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/images/icon/minimize_2_reduce_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_max_and_reduction.setIcon(icon3)
        self.pushButton_max_and_reduction.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_max_and_reduction.setFlat(True)
        self.pushButton_max_and_reduction.setObjectName("pushButton_max_and_reduction")
        self.horizontalLayout_control_window.addWidget(self.pushButton_max_and_reduction)
        self.pushButton_close = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_close.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_close.setToolTipDuration(3000)
        self.pushButton_close.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(255, 0, 0);\n"
"    border-radius:10px;\n"
"}\n"
".QPushButton:pressed{\n"
"    background-color:rgba(255, 0, 0, 190);\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_close.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/icon/close_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_close.setIcon(icon4)
        self.pushButton_close.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_close.setFlat(True)
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout_control_window.addWidget(self.pushButton_close)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_control_window)
        self.verticalLayout.addWidget(self.frame_menu)
        self.widget_view = QtWidgets.QWidget(self.frame)
        self.widget_view.setObjectName("widget_view")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_view)
        self.horizontalLayout_8.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.main_stacked_widget = QtWidgets.QStackedWidget(self.widget_view)
        self.main_stacked_widget.setStyleSheet("QWidget{\n"
"    background-color: transparent;\n"
"}")
        self.main_stacked_widget.setObjectName("main_stacked_widget")
        self.page_upload = QtWidgets.QWidget()
        self.page_upload.setObjectName("page_upload")
        self.horizontalLayout_upload = QtWidgets.QHBoxLayout(self.page_upload)
        self.horizontalLayout_upload.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_upload.setObjectName("horizontalLayout_upload")
        self.main_stacked_widget.addWidget(self.page_upload)
        self.page_image_view = QtWidgets.QWidget()
        self.page_image_view.setObjectName("page_image_view")
        self.main_stacked_widget.addWidget(self.page_image_view)
        self.horizontalLayout_8.addWidget(self.main_stacked_widget)
        self.verticalLayout.addWidget(self.widget_view)
        self.frame_function = QtWidgets.QFrame(self.frame)
        self.frame_function.setMinimumSize(QtCore.QSize(0, 84))
        self.frame_function.setStyleSheet(".QFrame#frame_function{\n"
"    background-color: rgb(32, 32, 32);\n"
"}")
        self.frame_function.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_function.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_function.setObjectName("frame_function")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_function)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_undo = QtWidgets.QPushButton(self.frame_function)
        self.pushButton_undo.setMinimumSize(QtCore.QSize(61, 61))
        self.pushButton_undo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_undo.setToolTipDuration(3000)
        self.pushButton_undo.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}\n"
".QPushButton:pressed{\n"
"    background-color:rgb(90, 90, 90);\n"
"    border-radius:10px;\n"
"}\n"
".QPushButton:normal{\n"
"    background-color:transparent;\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_undo.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/icon/undo_line_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_undo.setIcon(icon5)
        self.pushButton_undo.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_undo.setFlat(True)
        self.pushButton_undo.setObjectName("pushButton_undo")
        self.horizontalLayout_4.addWidget(self.pushButton_undo)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.pushButton_redo = QtWidgets.QPushButton(self.frame_function)
        self.pushButton_redo.setMinimumSize(QtCore.QSize(61, 61))
        self.pushButton_redo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_redo.setToolTipDuration(3000)
        self.pushButton_redo.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}\n"
".QPushButton:pressed{\n"
"    background-color:rgb(90, 90, 90);\n"
"    border-radius:10px;\n"
"}\n"
".QPushButton:normal{\n"
"    background-color:transparent;\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_redo.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/icon/redo_line_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_redo.setIcon(icon6)
        self.pushButton_redo.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_redo.setFlat(True)
        self.pushButton_redo.setObjectName("pushButton_redo")
        self.horizontalLayout_4.addWidget(self.pushButton_redo)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.pushButton_reset = QtWidgets.QPushButton(self.frame_function)
        self.pushButton_reset.setMinimumSize(QtCore.QSize(61, 61))
        self.pushButton_reset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_reset.setToolTipDuration(3000)
        self.pushButton_reset.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}\n"
".QPushButton:pressed{\n"
"    background-color:rgb(90, 90, 90);\n"
"    border-radius:10px;\n"
"}\n"
".QPushButton:normal{\n"
"    background-color:transparent;\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_reset.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/icon/circulate_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_reset.setIcon(icon7)
        self.pushButton_reset.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_reset.setFlat(True)
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.horizontalLayout_4.addWidget(self.pushButton_reset)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_4)
        self.separator = QtWidgets.QWidget(self.frame_function)
        self.separator.setMinimumSize(QtCore.QSize(60, 65))
        self.separator.setStyleSheet("image:url(:/images/icon/vertical_line_icon.svg);\n"
"background-color: transparent;")
        self.separator.setObjectName("separator")
        self.horizontalLayout_7.addWidget(self.separator)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_crop = QtWidgets.QPushButton(self.frame_function)
        self.pushButton_crop.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_crop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_crop.setToolTipDuration(3000)
        self.pushButton_crop.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}\n"
".QPushButton:pressed{\n"
"    background-color:rgb(90, 90, 90);\n"
"    border-radius:10px;\n"
"}\n"
".QPushButton:normal{\n"
"    background-color:transparent;\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_crop.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/icon/crop_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_crop.setIcon(icon8)
        self.pushButton_crop.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_crop.setFlat(True)
        self.pushButton_crop.setObjectName("pushButton_crop")
        self.horizontalLayout_6.addWidget(self.pushButton_crop)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.pushButton_rotate = QtWidgets.QPushButton(self.frame_function)
        self.pushButton_rotate.setMinimumSize(QtCore.QSize(61, 57))
        self.pushButton_rotate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_rotate.setToolTipDuration(3000)
        self.pushButton_rotate.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}\n"
".QPushButton:pressed{\n"
"    background-color:rgb(90, 90, 90);\n"
"    border-radius:10px;\n"
"}\n"
".QPushButton:normal{\n"
"    background-color:transparent;\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_rotate.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/images/icon/rotate_cw_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_rotate.setIcon(icon9)
        self.pushButton_rotate.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_rotate.setFlat(True)
        self.pushButton_rotate.setObjectName("pushButton_rotate")
        self.horizontalLayout_6.addWidget(self.pushButton_rotate)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.pushButton_curve = QtWidgets.QPushButton(self.frame_function)
        self.pushButton_curve.setMinimumSize(QtCore.QSize(61, 57))
        self.pushButton_curve.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_curve.setToolTipDuration(3000)
        self.pushButton_curve.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}\n"
".QPushButton:pressed{\n"
"    background-color:rgb(90, 90, 90);\n"
"    border-radius:10px;\n"
"}\n"
".QPushButton:normal{\n"
"    background-color:transparent;\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_curve.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/images/icon/curve_adjustment_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_curve.setIcon(icon10)
        self.pushButton_curve.setIconSize(QtCore.QSize(43, 43))
        self.pushButton_curve.setFlat(True)
        self.pushButton_curve.setObjectName("pushButton_curve")
        self.horizontalLayout_6.addWidget(self.pushButton_curve)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.pushButton_face = QtWidgets.QPushButton(self.frame_function)
        self.pushButton_face.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_face.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_face.setToolTipDuration(3000)
        self.pushButton_face.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}\n"
".QPushButton:pressed{\n"
"    background-color:rgb(90, 90, 90);\n"
"    border-radius:10px;\n"
"}\n"
".QPushButton:normal{\n"
"    background-color:transparent;\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_face.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/images/icon/face_smile_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_face.setIcon(icon11)
        self.pushButton_face.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_face.setFlat(True)
        self.pushButton_face.setObjectName("pushButton_face")
        self.horizontalLayout_6.addWidget(self.pushButton_face)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.pushButton_text = QtWidgets.QPushButton(self.frame_function)
        self.pushButton_text.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_text.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_text.setToolTipDuration(3000)
        self.pushButton_text.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}\n"
".QPushButton:pressed{\n"
"    background-color:rgb(90, 90, 90);\n"
"    border-radius:10px;\n"
"}\n"
".QPushButton:normal{\n"
"    background-color:transparent;\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_text.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/images/icon/type_text_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_text.setIcon(icon12)
        self.pushButton_text.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_text.setFlat(True)
        self.pushButton_text.setObjectName("pushButton_text")
        self.horizontalLayout_6.addWidget(self.pushButton_text)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.pushButton_adjust = QtWidgets.QPushButton(self.frame_function)
        self.pushButton_adjust.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_adjust.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_adjust.setToolTipDuration(3000)
        self.pushButton_adjust.setStyleSheet(".QPushButton:hover{\n"
"    background-color:rgb(58, 58, 58);\n"
"    border-radius:10px;\n"
"}\n"
".QPushButton:pressed{\n"
"    background-color:rgb(90, 90, 90);\n"
"    border-radius:10px;\n"
"}\n"
".QPushButton:normal{\n"
"    background-color:transparent;\n"
"    border-radius:10px;\n"
"}")
        self.pushButton_adjust.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/images/icon/adjust_control_con.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_adjust.setIcon(icon13)
        self.pushButton_adjust.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_adjust.setFlat(True)
        self.pushButton_adjust.setObjectName("pushButton_adjust")
        self.horizontalLayout_6.addWidget(self.pushButton_adjust)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7.setStretch(0, 4)
        self.horizontalLayout_7.setStretch(1, 1)
        self.horizontalLayout_7.setStretch(2, 12)
        self.verticalLayout.addWidget(self.frame_function)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 15)
        self.verticalLayout.setStretch(2, 2)
        self.horizontalLayout_5.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.main_stacked_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_logo.setText(_translate("MainWindow", "image-editor"))
        self.pushButton_zoom_in.setToolTip(_translate("MainWindow", "放大"))
        self.pushButton_zoom_out.setToolTip(_translate("MainWindow", "缩小"))
        self.pushButton_min.setToolTip(_translate("MainWindow", "最小化"))
        self.pushButton_max_and_reduction.setToolTip(_translate("MainWindow", "最大化"))
        self.pushButton_close.setToolTip(_translate("MainWindow", "关闭"))
        self.pushButton_undo.setToolTip(_translate("MainWindow", "撤销"))
        self.pushButton_redo.setToolTip(_translate("MainWindow", "恢复"))
        self.pushButton_reset.setToolTip(_translate("MainWindow", "重置"))
        self.pushButton_crop.setToolTip(_translate("MainWindow", "裁剪"))
        self.pushButton_rotate.setToolTip(_translate("MainWindow", "旋转"))
        self.pushButton_curve.setToolTip(_translate("MainWindow", "曲线调色"))
        self.pushButton_face.setToolTip(_translate("MainWindow", "人脸"))
        self.pushButton_text.setToolTip(_translate("MainWindow", "文字"))
        self.pushButton_adjust.setToolTip(_translate("MainWindow", "调节"))
import resources_rc
