# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_xml/widget_face_area.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(331, 514)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_hist = QtWidgets.QWidget(Form)
        self.widget_hist.setStyleSheet("QWidget{\n"
"    border-radius:20px;\n"
"    background-color: rgb(32, 32, 32);\n"
"}\n"
"QScrollBar:horizontal{\n"
"    height:8px;\n"
"    background:rgba(0,0,0,0%);\n"
"border-radius:4px;\n"
"\n"
"}\n"
"QScrollBar::handle:horizontal{\n"
"    background:rgba(255,255,255,50%);\n"
"border-radius:4px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover{\n"
"    background:rgba(255,255,255,100%);\n"
"    min-width:0;\n"
"}\n"
"QScrollBar::add-line:horizontal{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::sub-line:horizontal{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::add-line:horizontal:hover{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::add-page:horizontal,QScrollBar::sub-page:horizontal\n"
"{\n"
"    background:rgba(0,0,0,10%);\n"
"    border-radius:4px;\n"
"}\n"
"\n"
"QScrollBar:vertical{\n"
"    width:8px;\n"
"    background:rgba(0,0,0,0%);\n"
"\n"
"}\n"
"QScrollBar::handle:vertical{\n"
"    width:0px;\n"
"    background:rgba(255,255,255,50%);\n"
"    border-radius:4px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{\n"
"    width:0px;\n"
"    background:rgba(255,255,255,100%);\n"
"    border-radius:4px;\n"
"    min-width:20;\n"
"}\n"
"QScrollBar::add-line:vertical{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::sub-line:vertical{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::add-line:vertical:hover{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::sub-line:vertical:hover{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::add-page:vertical,QScrollBar::sub-page:vertical\n"
"{\n"
"    background:rgba(0,0,0,10%);\n"
"    border-radius:4px;\n"
"}\n"
"\n"
" \n"
" \n"
"QSlider::add-page:horizontal {\n"
"    background-color: qlineargradient(spread: pad, x1: 0, y1: 1, x2: 1, y2: 1,\n"
"                                      stop: 0 rgb(100, 100, 100),\n"
"                                      stop: 1 rgb(255, 78, 0,));\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background-color: qlineargradient(spread: pad, x1: 0, y1: 1, x2: 1, y2: 1,\n"
"                                      stop: 0 rgb(51, 151, 255),\n"
"                                      stop: 1 rgb(100, 100, 100));\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    background: transparent;\n"
"    height: 8px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    width: 16px;\n"
"    height: 18px;\n"
"    margin: -4px 0px -4px 0px;\n"
"    border-radius: 8px;\n"
"    background: white;\n"
"}\n"
"")
        self.widget_hist.setObjectName("widget_hist")
        self.horizontalLayout_hist = QtWidgets.QHBoxLayout(self.widget_hist)
        self.horizontalLayout_hist.setObjectName("horizontalLayout_hist")
        self.scrollArea = QtWidgets.QScrollArea(self.widget_hist)
        self.scrollArea.setStyleSheet("QScrollArea{\n"
"    background-color: transparent;\n"
"}")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 309, 492))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_equalize_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_equalize_2.sizePolicy().hasHeightForWidth())
        self.widget_equalize_2.setSizePolicy(sizePolicy)
        self.widget_equalize_2.setObjectName("widget_equalize_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_equalize_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_face = QtWidgets.QLabel(self.widget_equalize_2)
        self.label_face.setMinimumSize(QtCore.QSize(140, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_face.setFont(font)
        self.label_face.setStyleSheet("QLabel{\n"
"    color:rgb(255, 255, 255);\n"
"}")
        self.label_face.setObjectName("label_face")
        self.horizontalLayout_3.addWidget(self.label_face)
        self.label_face_num = QtWidgets.QLabel(self.widget_equalize_2)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_face_num.setFont(font)
        self.label_face_num.setStyleSheet("QLabel{\n"
"    color:rgb(255, 255, 255);\n"
"}")
        self.label_face_num.setObjectName("label_face_num")
        self.horizontalLayout_3.addWidget(self.label_face_num)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.widget_equalize_2)
        self.widget_equalize_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_equalize_3.sizePolicy().hasHeightForWidth())
        self.widget_equalize_3.setSizePolicy(sizePolicy)
        self.widget_equalize_3.setObjectName("widget_equalize_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_equalize_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.label_hist_2 = QtWidgets.QLabel(self.widget_equalize_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_hist_2.sizePolicy().hasHeightForWidth())
        self.label_hist_2.setSizePolicy(sizePolicy)
        self.label_hist_2.setMinimumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_hist_2.setFont(font)
        self.label_hist_2.setStyleSheet("QLabel{\n"
"    color:rgb(255, 255, 255);\n"
"}")
        self.label_hist_2.setObjectName("label_hist_2")
        self.horizontalLayout_4.addWidget(self.label_hist_2)
        self.widget_switch_button_2 = QtWidgets.QWidget(self.widget_equalize_3)
        self.widget_switch_button_2.setMinimumSize(QtCore.QSize(60, 30))
        self.widget_switch_button_2.setObjectName("widget_switch_button_2")
        self.horizontalLayout_switch_camera = QtWidgets.QHBoxLayout(self.widget_switch_button_2)
        self.horizontalLayout_switch_camera.setContentsMargins(0, 0, 3, 0)
        self.horizontalLayout_switch_camera.setObjectName("horizontalLayout_switch_camera")
        self.horizontalLayout_4.addWidget(self.widget_switch_button_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.widget_equalize_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_hist.addWidget(self.scrollArea)
        self.horizontalLayout.addWidget(self.widget_hist)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_face.setText(_translate("Form", "检测到人脸数："))
        self.label_face_num.setText(_translate("Form", "0"))
        self.label_hist_2.setText(_translate("Form", "摄像头："))
import resources_rc
