# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_xml/widget_face_area.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(331, 514)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_hist = QtWidgets.QWidget(Form)
        self.widget_hist.setStyleSheet("QWidget{\n"
"                            border-radius:20px;\n"
"                            background-color: rgb(32, 32, 32);\n"
"                            }\n"
"                            QScrollBar:horizontal{\n"
"                            height:8px;\n"
"                            background:rgba(0,0,0,0%);\n"
"                            border-radius:4px;\n"
"\n"
"                            }\n"
"                            QScrollBar::handle:horizontal{\n"
"                            background:rgba(255,255,255,50%);\n"
"                            border-radius:4px;\n"
"                            }\n"
"                            QScrollBar::handle:horizontal:hover{\n"
"                            background:rgba(255,255,255,100%);\n"
"                            min-width:0;\n"
"                            }\n"
"                            QScrollBar::add-line:horizontal{\n"
"                            height:0px;width:0px;\n"
"\n"
"                            }\n"
"                            QScrollBar::sub-line:horizontal{\n"
"                            height:0px;width:0px;\n"
"\n"
"                            }\n"
"                            QScrollBar::add-line:horizontal:hover{\n"
"                            height:0px;width:0px;\n"
"\n"
"                            }\n"
"                            QScrollBar::sub-line:horizontal:hover{\n"
"                            height:0px;width:0px;\n"
"\n"
"                            }\n"
"                            QScrollBar::add-page:horizontal,QScrollBar::sub-page:horizontal\n"
"                            {\n"
"                            background:rgba(0,0,0,10%);\n"
"                            border-radius:4px;\n"
"                            }\n"
"\n"
"                            QScrollBar:vertical{\n"
"                            width:8px;\n"
"                            background:rgba(0,0,0,0%);\n"
"\n"
"                            }\n"
"                            QScrollBar::handle:vertical{\n"
"                            width:0px;\n"
"                            background:rgba(255,255,255,50%);\n"
"                            border-radius:4px;\n"
"                            }\n"
"                            QScrollBar::handle:vertical:hover{\n"
"                            width:0px;\n"
"                            background:rgba(255,255,255,100%);\n"
"                            border-radius:4px;\n"
"                            min-width:20;\n"
"                            }\n"
"                            QScrollBar::add-line:vertical{\n"
"                            height:0px;width:0px;\n"
"\n"
"                            }\n"
"                            QScrollBar::sub-line:vertical{\n"
"                            height:0px;width:0px;\n"
"\n"
"                            }\n"
"                            QScrollBar::add-line:vertical:hover{\n"
"                            height:0px;width:0px;\n"
"\n"
"                            }\n"
"                            QScrollBar::sub-line:vertical:hover{\n"
"                            height:0px;width:0px;\n"
"\n"
"                            }\n"
"                            QScrollBar::add-page:vertical,QScrollBar::sub-page:vertical\n"
"                            {\n"
"                            background:rgba(0,0,0,10%);\n"
"                            border-radius:4px;\n"
"                            }\n"
"\n"
"\n"
"                            QSlider::add-page:horizontal {\n"
"                            background-color: qlineargradient(spread: pad, x1: 0, y1: 1, x2: 1, y2: 1,\n"
"                            stop: 0 rgb(100, 100, 100),\n"
"                            stop: 1 rgb(255, 78, 0,));\n"
"                            border-radius: 4px;\n"
"                            }\n"
"\n"
"                            QSlider::sub-page:horizontal {\n"
"                            background-color: qlineargradient(spread: pad, x1: 0, y1: 1, x2: 1, y2: 1,\n"
"                            stop: 0 rgb(51, 151, 255),\n"
"                            stop: 1 rgb(100, 100, 100));\n"
"                            border-radius: 4px;\n"
"                            }\n"
"\n"
"                            QSlider::groove:horizontal {\n"
"                            background: transparent;\n"
"                            height: 8px;\n"
"                            }\n"
"\n"
"                            QSlider::handle:horizontal {\n"
"                            width: 16px;\n"
"                            height: 18px;\n"
"                            margin: -4px 0px -4px 0px;\n"
"                            border-radius: 8px;\n"
"                            background: white;\n"
"                            }\n"
"                        ")
        self.widget_hist.setObjectName("widget_hist")
        self.horizontalLayout_hist = QtWidgets.QHBoxLayout(self.widget_hist)
        self.horizontalLayout_hist.setObjectName("horizontalLayout_hist")
        self.scrollArea = QtWidgets.QScrollArea(self.widget_hist)
        self.scrollArea.setStyleSheet("QScrollArea{\n"
"                                        background-color: transparent;\n"
"                                        }\n"
"                                    ")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 309, 492))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_face_num = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_face_num.sizePolicy().hasHeightForWidth())
        self.widget_face_num.setSizePolicy(sizePolicy)
        self.widget_face_num.setObjectName("widget_face_num")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_face_num)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_face = QtWidgets.QLabel(self.widget_face_num)
        self.label_face.setMinimumSize(QtCore.QSize(140, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_face.setFont(font)
        self.label_face.setStyleSheet("QLabel{\n"
"                                                                    color:rgb(255, 255, 255);\n"
"                                                                    }\n"
"                                                                ")
        self.label_face.setObjectName("label_face")
        self.horizontalLayout_3.addWidget(self.label_face)
        self.label_face_num = QtWidgets.QLabel(self.widget_face_num)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_face_num.setFont(font)
        self.label_face_num.setStyleSheet("QLabel{\n"
"                                                                    color:rgb(255, 255, 255);\n"
"                                                                    }\n"
"                                                                ")
        self.label_face_num.setObjectName("label_face_num")
        self.horizontalLayout_3.addWidget(self.label_face_num)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.widget_face_num)
        self.widget_camera = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_camera.sizePolicy().hasHeightForWidth())
        self.widget_camera.setSizePolicy(sizePolicy)
        self.widget_camera.setObjectName("widget_camera")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_camera)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.label_camera = QtWidgets.QLabel(self.widget_camera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_camera.sizePolicy().hasHeightForWidth())
        self.label_camera.setSizePolicy(sizePolicy)
        self.label_camera.setMinimumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_camera.setFont(font)
        self.label_camera.setStyleSheet("QLabel{\n"
"                                                                    color:rgb(255, 255, 255);\n"
"                                                                    }\n"
"                                                                ")
        self.label_camera.setObjectName("label_camera")
        self.horizontalLayout_4.addWidget(self.label_camera)
        self.widget_switch_button_camera = QtWidgets.QWidget(self.widget_camera)
        self.widget_switch_button_camera.setMinimumSize(QtCore.QSize(60, 30))
        self.widget_switch_button_camera.setObjectName("widget_switch_button_camera")
        self.horizontalLayout_switch_camera = QtWidgets.QHBoxLayout(self.widget_switch_button_camera)
        self.horizontalLayout_switch_camera.setContentsMargins(0, 0, 3, 0)
        self.horizontalLayout_switch_camera.setObjectName("horizontalLayout_switch_camera")
        self.horizontalLayout_4.addWidget(self.widget_switch_button_camera)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.widget_camera)
        self.widget_face_rect = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_face_rect.sizePolicy().hasHeightForWidth())
        self.widget_face_rect.setSizePolicy(sizePolicy)
        self.widget_face_rect.setObjectName("widget_face_rect")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_face_rect)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.label_face_rect = QtWidgets.QLabel(self.widget_face_rect)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_face_rect.sizePolicy().hasHeightForWidth())
        self.label_face_rect.setSizePolicy(sizePolicy)
        self.label_face_rect.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_face_rect.setFont(font)
        self.label_face_rect.setStyleSheet("QLabel{\n"
"                                                                    color:rgb(255, 255, 255);\n"
"                                                                    }\n"
"                                                                ")
        self.label_face_rect.setObjectName("label_face_rect")
        self.horizontalLayout_5.addWidget(self.label_face_rect)
        self.widget_switch_button_rect = QtWidgets.QWidget(self.widget_face_rect)
        self.widget_switch_button_rect.setMinimumSize(QtCore.QSize(60, 30))
        self.widget_switch_button_rect.setObjectName("widget_switch_button_rect")
        self.horizontalLayout_switch_rect = QtWidgets.QHBoxLayout(self.widget_switch_button_rect)
        self.horizontalLayout_switch_rect.setContentsMargins(0, 0, 3, 0)
        self.horizontalLayout_switch_rect.setObjectName("horizontalLayout_switch_rect")
        self.horizontalLayout_5.addWidget(self.widget_switch_button_rect)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout.addWidget(self.widget_face_rect)
        self.widget_skin = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_skin.setMinimumSize(QtCore.QSize(0, 88))
        self.widget_skin.setMaximumSize(QtCore.QSize(16777215, 88))
        self.widget_skin.setObjectName("widget_skin")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_skin)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_skin = QtWidgets.QHBoxLayout()
        self.horizontalLayout_skin.setObjectName("horizontalLayout_skin")
        self.label_image_skin = QtWidgets.QLabel(self.widget_skin)
        self.label_image_skin.setMinimumSize(QtCore.QSize(30, 30))
        self.label_image_skin.setStyleSheet("\n"
"                                                                            image:url(:/images/icon/skin_smooth.svg)\n"
"                                                                        ")
        self.label_image_skin.setText("")
        self.label_image_skin.setObjectName("label_image_skin")
        self.horizontalLayout_skin.addWidget(self.label_image_skin)
        self.label_text_skin = QtWidgets.QLabel(self.widget_skin)
        self.label_text_skin.setMinimumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias
                                                                            )
        self.label_text_skin.setFont(font)
        self.label_text_skin.setStyleSheet("QLabel{\n"
"                                                                            color:rgb(255, 255, 255);\n"
"                                                                            }\n"
"                                                                        ")
        self.label_text_skin.setObjectName("label_text_skin")
        self.horizontalLayout_skin.addWidget(self.label_text_skin)
        self.label_smooth_value = QtWidgets.QLabel(self.widget_skin)
        self.label_smooth_value.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias
                                                                            )
        self.label_smooth_value.setFont(font)
        self.label_smooth_value.setStyleSheet("QLabel{\n"
"                                                                            color:rgb(255, 255, 255);\n"
"                                                                            }\n"
"                                                                        ")
        self.label_smooth_value.setObjectName("label_smooth_value")
        self.horizontalLayout_skin.addWidget(self.label_smooth_value)
        self.horizontalLayout_skin.setStretch(0, 1)
        self.horizontalLayout_skin.setStretch(1, 4)
        self.horizontalLayout_skin.setStretch(2, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_skin)
        self.slider_smooth_skin = QtWidgets.QSlider(self.widget_skin)
        self.slider_smooth_skin.setStyleSheet("")
        self.slider_smooth_skin.setMinimum(0)
        self.slider_smooth_skin.setMaximum(100)
        self.slider_smooth_skin.setOrientation(QtCore.Qt.Horizontal)
        self.slider_smooth_skin.setObjectName("slider_smooth_skin")
        self.verticalLayout_4.addWidget(self.slider_smooth_skin)
        self.verticalLayout.addWidget(self.widget_skin)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_hist.addWidget(self.scrollArea)
        self.horizontalLayout.addWidget(self.widget_hist)

        self.retranslateUi(Form)
        self.slider_smooth_skin.valueChanged['int'].connect(self.label_smooth_value.setNum) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_face.setText(_translate("Form", "检测到人脸数："))
        self.label_face_num.setText(_translate("Form", "0"))
        self.label_camera.setText(_translate("Form", "摄像头："))
        self.label_face_rect.setText(_translate("Form", "人脸检测框："))
        self.label_text_skin.setText(_translate("Form", "磨皮"))
        self.label_smooth_value.setText(_translate("Form", "0"))
import resources_rc
