# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_xml/widget_upload_image.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(550, 300)
        Form.setMinimumSize(QtCore.QSize(550, 300))
        Form.setMaximumSize(QtCore.QSize(550, 300))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_upload = QtWidgets.QWidget(Form)
        self.widget_upload.setMinimumSize(QtCore.QSize(550, 300))
        self.widget_upload.setMaximumSize(QtCore.QSize(550, 300))
        self.widget_upload.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.widget_upload.setStyleSheet(".QWidget#widget_upload{\n"
"                            border: 5px dashed #ccc;\n"
"                            border-radius:10px;\n"
"                            background-color:transparent;\n"
"                            }\n"
"                            .QWidget#widget_upload:hover{\n"
"                            background-color: rgba(0, 170, 255, 50);\n"
"                            }\n"
"                        ")
        self.widget_upload.setObjectName("widget_upload")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_upload)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.widget_cloud = QtWidgets.QWidget(self.widget_upload)
        self.widget_cloud.setMinimumSize(QtCore.QSize(161, 141))
        self.widget_cloud.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.widget_cloud.setStyleSheet("QWidget{\n"
"                                        image:url(:/images/icon/download_cloud_multimedia_icon.svg);\n"
"                                        background-color: transparent;\n"
"                                        }\n"
"                                    ")
        self.widget_cloud.setObjectName("widget_cloud")
        self.verticalLayout_2.addWidget(self.widget_cloud)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.label_drag = QtWidgets.QLabel(self.widget_upload)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_drag.setFont(font)
        self.label_drag.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_drag.setStyleSheet("QLabel{\n"
"                                                background-color:transparent;\n"
"                                                color: rgb(255, 255, 255);\n"
"                                                }\n"
"                                            ")
        self.label_drag.setObjectName("label_drag")
        self.horizontalLayout_9.addWidget(self.label_drag)
        self.label_upload = QtWidgets.QLabel(self.widget_upload)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(15)
        self.label_upload.setFont(font)
        self.label_upload.setStyleSheet("QLabel{\n"
"                                                background-color:transparent;\n"
"                                                color: rgb(64, 158, 255);\n"
"                                                }\n"
"                                            ")
        self.label_upload.setObjectName("label_upload")
        self.horizontalLayout_9.addWidget(self.label_upload)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout.addWidget(self.widget_upload)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_drag.setText(_translate("Form", "将图片拖拽到此处，或"))
        self.label_upload.setText(_translate("Form", "点击上传"))
import resources_rc
